### ISSUE TITLE
problem while executing

### ISSUE THREAD

**Issue by Sherl0ck007** [hypery2k/grunt-galenframework#23]
After running the "grunt-galen" task i received the following error message:

Running "galen:local" (galen) task
Starting local Galen
    • tests/galen.test.js
Fatal error: Command failed: galen test tests/galen.test.js  --htmlreport report    -Dwebdriver.chrome.driver=[REPLACEDPATH]\node_modules\chromedriver\bin\chromedriver -Dwebdriver.gecko.driver=[REPLACEDPATH]\node_modules\geckodriver\bin\geckodriver
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: [REPLACEDPATH]\node_modules\chromedriver\bin\chromedriver
        at com.galenframework.GalenMain.execute(GalenMain.java:60)
        at com.galenframework.GalenMain.main(GalenMain.java:78)
Caused by: java.io.FileNotFoundException:[REPLACEDPATH]\node_modules\chromedriver\bin\chromedriver
        at com.galenframework.actions.GalenActionTest.execute(GalenActionTest.java:82)
        at com.galenframework.GalenMain.execute(GalenMain.java:58)
        ... 1 more

**Comment by hypery2k** [comment]
which node version you're using?

**Comment by Sherl0ck007** [comment]
Node version is v7.6.0

**Comment by hypery2k** [comment]
can you post the output of the following commands:
```
ls -lisah node_modules | grep chromedriver
ls -lisah node_modules\grunt-galenframework\node_modules | grep chromedriver
```

**Comment by Sherl0ck007** [comment]
output for the first command is the following: 
1970324837054189 4.0K drwxr-xr-x 1 sarahz 1049089 0 Feb 24 11:55 chromedriver/
the second command does not do anything

**Comment by Sherl0ck007** [comment]
In the meantime, i switched to another pc and am now getting a "unknown browser factory" error in the galen.test.js file in this method:

forAll(config.getDevices(), function (device) {
// [injector:spec] --> this is the line where the error occurs
....injected test methods...
// [endinjector]

**Comment by hypery2k** [comment]
could you try if it's working after running this:
```
npm install grunt-galenframework@2.3.2-9 --E --S
```

**Comment by Sherl0ck007** [comment]
the issue was resolved after re-installing all galenframework npm modules
