### ISSUE TITLE
any reason for no inject method

### ISSUE THREAD

**Issue by ducci91** [hypery2k/grunt-galenframework#37]
hello, thanks for the great work. I wonder why there is no inject method available to inject javascript?

**Comment by hypery2k** [comment]
no real reason, just not that much time. Feel free to sent a PR

**Comment by ducci91** [comment]
hello, thanks for your message. I already sent PR here:
https://github.com/hypery2k/grunt-galenframework/pull/38

I don't know how you handle versioning, thats why I think you need to update it after accepting my PR
thanks and best
duc

**Comment by hypery2k** [comment]
merged your PR and will try to verify it later. Please use develop branch next time ;)

**Comment by ducci91** [comment]
alright thank you. oh okay, thank you for the hint. when will you think you
will update it so it is installable via npm?

Martin Reinhardt <notifications@github.com> schrieb am Mi. 23. Aug. 2017 um
10:16:

**Comment by hypery2k** [comment]
you can try installing a snaphot: `grunt-galenframework@2.3.4-develop-21`

**Comment by hypery2k** [comment]
version 2.3.5 is released
